-- قم بتشغيل هذا الكود في Supabase SQL Editor لإنشاء الجداول الخاصة بالضيوف (Guest Mode)

-- 1. إنشاء جدول معاملات الضيوف
CREATE TABLE IF NOT EXISTS guest_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_year TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 2. إنشاء جدول أصول الضيوف (الذهب)
CREATE TABLE IF NOT EXISTS guest_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    purchase_price_total NUMERIC NOT NULL,
    purchase_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- 3. إنشاء جدول أهداف الضيوف (إن وُجد)
CREATE TABLE IF NOT EXISTS guest_financial_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_name TEXT NOT NULL,
    target_amount NUMERIC NOT NULL,
    current_amount NUMERIC DEFAULT 0,
    deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. إعدادات الضيوف (الرصيد الافتتاحي)
CREATE TABLE IF NOT EXISTS guest_app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. نسخ أسعار الذهب الحالية للضيوف (هذا الجدول يمكن أن يستخدم الجدول الأصلي إذا لم يكن هناك إدخال خاص به، لكن الأفضل فصله لتجنب أي أخطاء)
CREATE TABLE IF NOT EXISTS guest_gold_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type TEXT NOT NULL,
    buy_price NUMERIC NOT NULL,
    sell_price NUMERIC NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- تعبئة أسعار الذهب الأولية للضيوف
INSERT INTO guest_gold_prices (asset_type, buy_price, sell_price)
VALUES ('gold_english_pound', 400, 410)
ON CONFLICT DO NOTHING;

-- إضافة رصيد افتتاحي للضيف
INSERT INTO guest_app_settings (key, value)
VALUES ('opening_balance', '5000')
ON CONFLICT DO NOTHING;

-- إضافة بعض البيانات الوهمية لتجميل لوحة تحكم الضيف
INSERT INTO guest_transactions (month_year, description, amount, type, category)
VALUES 
(to_char(now(), 'YYYY-MM'), 'راتب شهري', 3000, 'income', 'رواتب'),
(to_char(now(), 'YYYY-MM'), 'إيجار المنزل', 400, 'expense', 'منزل'),
(to_char(now(), 'YYYY-MM'), 'تسوق سوبرماركت', 150, 'expense', 'طعام'),
(to_char(now(), 'YYYY-MM'), 'فاتورة كهرباء', 40, 'expense', 'فواتير'),
(to_char(now(), 'YYYY-MM'), 'عمل حر', 500, 'income', 'عمل');

INSERT INTO guest_assets (asset_type, quantity, purchase_price_total, purchase_date)
VALUES ('gold_english_pound', 2, 800, now());
