/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as MonthsIndexRouteImport } from './routes/months.index'
import { Route as MonthsMonthYearRouteImport } from './routes/months.$monthYear'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthsIndexRoute = MonthsIndexRouteImport.update({
  id: '/months/',
  path: '/months/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthsMonthYearRoute = MonthsMonthYearRouteImport.update({
  id: '/months/$monthYear',
  path: '/months/$monthYear',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/assets': typeof AssetsRoute
  '/compare': typeof CompareRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/trash': typeof TrashRoute
  '/months/$monthYear': typeof MonthsMonthYearRoute
  '/months/': typeof MonthsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/assets': typeof AssetsRoute
  '/compare': typeof CompareRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/trash': typeof TrashRoute
  '/months/$monthYear': typeof MonthsMonthYearRoute
  '/months': typeof MonthsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/assets': typeof AssetsRoute
  '/compare': typeof CompareRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/trash': typeof TrashRoute
  '/months/$monthYear': typeof MonthsMonthYearRoute
  '/months/': typeof MonthsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/assets'
    | '/compare'
    | '/reports'
    | '/search'
    | '/trash'
    | '/months/$monthYear'
    | '/months/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/assets'
    | '/compare'
    | '/reports'
    | '/search'
    | '/trash'
    | '/months/$monthYear'
    | '/months'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/assets'
    | '/compare'
    | '/reports'
    | '/search'
    | '/trash'
    | '/months/$monthYear'
    | '/months/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AssetsRoute: typeof AssetsRoute
  CompareRoute: typeof CompareRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  TrashRoute: typeof TrashRoute
  MonthsMonthYearRoute: typeof MonthsMonthYearRoute
  MonthsIndexRoute: typeof MonthsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/months/': {
      id: '/months/'
      path: '/months'
      fullPath: '/months/'
      preLoaderRoute: typeof MonthsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/months/$monthYear': {
      id: '/months/$monthYear'
      path: '/months/$monthYear'
      fullPath: '/months/$monthYear'
      preLoaderRoute: typeof MonthsMonthYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AssetsRoute: AssetsRoute,
  CompareRoute: CompareRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  TrashRoute: TrashRoute,
  MonthsMonthYearRoute: MonthsMonthYearRoute,
  MonthsIndexRoute: MonthsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
